### ISSUE TITLE
Wallet Connect Integration

### ISSUE THREAD

**Issue by riveign** [Psychedelic/plug-mobile#394] opened 2022-08-11 12:22 UTC
# Description

**Task:**

Wallet Connect Implementation

**Figma Ticket [[here](https://www.figma.com/file/no61f8MMPQlPUIaXSX3zCn/Plug---Wallet?node-id=7699%3A1928)](https://www.figma.com/file/no61f8MMPQlPUIaXSX3zCn/Plug---Wallet?node-id=7699%3A1928)**

- [ ] Pending Request call
- [ ] App views https://www.figma.com/file/no61f8MMPQlPUIaXSX3zCn/Plug---Wallet?node-id=9773%3A7295

**Comment by alinasytnik** [comment] 2022-10-07 17:31
## **⚠️Bug**

## Description
After declining the permission, the user is unable to reconnect the wallet because of permanent loading.

## Steps to Reproduce
1. Go to Sonic
2. Click on Connect button in the Sonic app
3. Confirm the connection by clicking on Connect button in the Plug app
4. On the permission step, decline the connection. (It'll take you back to the Sonic app)
5. Try to reconnect your wallet.
**Current:** Notice that the connection is loading permanently, and it does not allow reconnecting the wallet

## Expected behavior
The app should have the ability to reconnect to a wallet.

## Screenshots
https://user-images.githubusercontent.com/33018206/194613217-6c613c92-956c-4c54-adb6-c830d75e0fc3.MP4


## Smartphone (please complete the following information):
 - Device: iPhone 14
 - OS: iOS 16.0.1
 - Version 0.3.0(3)

**Comment by alinasytnik** [comment] 2022-10-07 17:41
## **⚠️Bug**

## Description
After reloading the page, the wallet is disconnected

## Steps to Reproduce
1. Go to Sonic
2. Click on Connect button in the Sonic app
3. Confirm the connection by clicking on Connect button in the Plug app
4. Allow the permissions (It'll take you back to the Sonic app)
5. Reload the Sonic app page. 
**Current:** Notice that the wallet was disconnected.

## Expected behavior
The wallet shouldn't be disconnected after the Sonic app page refresh.

## Screenshots

https://user-images.githubusercontent.com/33018206/194616335-e78fc99e-6c2d-42ce-ae72-dbf15d017d70.MP4



## Smartphone (please complete the following information):
 - Device: iPhone 14
 - OS: iOS 16.0.1
 - Version 0.3.0(3)

**Comment by alinasytnik** [comment] 2022-10-12 16:45
## **⚠️Bug**

## Description
ATKN -> NDP Swap cannot be processed because of long loading on the second step of permissions

## Steps to Reproduce
1. Go to Sonic
2. Click on Connect button in the Sonic app
3. Confirm the connection by clicking on Connect button in the Plug app
4. Allow the permissions (It'll take you back to the Sonic app)
5. Go to the Swap tab.
6. Choose ATKN and NDP swap pair. 
7.  Confirm the 1 Step of permissions.
8.  Try to confirm the 2 Step of permissions.
**Current:** Notice that 2 step doesn't appear and the app takes a long to load. 

## Expected behavior
2 Step of permissions should appear, and ATKN -> NDP Swap should be processed successfully. 

## Screenshots

Uploading RPReplay_Final1665591717.MP4…


## Smartphone:
 - Device: iPhone 14
 - OS: iOS 16.0.1
 - Version 0.3.0(6)

**Comment by alinasytnik** [comment] 2022-10-12 17:37
## **⚠️Bug**

## Description
GTKN Deposit cannot be processed because of long loading on the second step of permissions

## Steps to Reproduce
1. Go to Sonic
2. Click on Connect button in the Sonic app
3. Confirm the connection by clicking on Connect button in the Plug app
4. Allow the permissions (It'll take you back to the Sonic app)
5. Go to the Assets tab.
6. Choose GTKN Deposit option and try to deposit this asset. 
7.  Confirm the 1 Step of permissions.
8.  Try to confirm the 2 Step of permissions.
**Current:** Notice that 2 step doesn't appear and the app takes a long to load. 

## Expected behavior
2 Step of permissions should appear, and GTKN Depositing should be processed successfully. 

## Screenshots


https://user-images.githubusercontent.com/33018206/195409705-547cfc4e-595c-4265-bed8-d24fb088ca0b.MOV



## Smartphone:
 - Device: iPhone 14
 - OS: iOS 16.0.1
 - Version 0.3.0(6)

**Comment by alinasytnik** [comment] 2022-10-12 17:49
## **⚠️Bug**

## Description
OGYt + GTKN Liquidity add cannot be processed because of long loading on the second step of permissions

## Steps to Reproduce
1. Go to Sonic
2. Click on Connect button in the Sonic app
3. Confirm the connection by clicking on Connect button in the Plug app
4. Allow the permissions (It'll take you back to the Sonic app)
5. Go to the Liquidity tab.
6. Choose OGYt + GTKN liquidity pair. Try to add liquidity.
7.  Confirm the 1 Step of permissions.
8.  Try to confirm the 2 Step of permissions.
**Current:** Notice that 2 step doesn't appear and the app takes a long to load. 

## Expected behavior
2 Step of permissions should appear, and OGYt + GTKN Liquidity adding should be processed successfully. 

## Screenshots

https://user-images.githubusercontent.com/33018206/195412841-79688997-7583-424e-91d6-71db80fc8b32.MP4


## Smartphone:
 - Device: iPhone 14
 - OS: iOS 16.0.1
 - Version 0.3.0(6)

**Comment by alinasytnik** [comment] 2022-10-12 18:17
## **⚠️Bug**

## Description
After many performed actions in Sonic app, Wallet Connect stops identifying the Plug app on the mobile device and redirects the user to the Plug site each time he tries to connect again. To fix this, I had to reinstall the application.


## Steps to Reproduce
1. Go to Sonic
2. Try to perform many actions, such as swapping, withdrawing, and adding liquidity.
3. Reload the Sonic app
4. Try to reconnect the wallet.
**Current:** Notice that the user is taken to the plug.ooo although Plug Mobile is already installed on his mobile device.

## Expected behavior
If Plug Mobile is installed on the user's phone, after pressing the Connect button, he should be directed to the Plug app to confirm the connection.

## Screenshots


https://user-images.githubusercontent.com/33018206/195418111-7ec9c341-c470-4de4-a25c-0252b1f5971f.mov



## Smartphone:
 - Device: iPhone 14
 - OS: iOS 16.0.1
 - Version 0.3.0(6)

**Comment by alinasytnik** [comment] 2022-10-20 13:46
## **⚠️Bug**

## Description
After declining (and canceling) the permission (and the connection), the user cannot reconnect the wallet because of permanent loading.

## Steps to Reproduce
1. Go to Sonic
2. Click on Connect button in the Sonic app
3. Cancel the connection by clicking on the Cancel button in the Plug app. (It'll take you back to Sonic.)
4. Try to reconnect your wallet.
**Current:** Notice that the connection is loading permanently, and it does not allow reconnecting the wallet
5. Click on Connect button in the Sonic app
6. Confirm the connection by clicking on Connect button in the Plug app
7. On the permission step, decline the connection. (It'll take you back to the Sonic app)
8. Try to reconnect your wallet.
**Current:** Notice that the connection is loading permanently, and it does not allow reconnecting the wallet

## Expected behavior
The app should have the ability to reconnect to the wallet.

## Screenshots

https://user-images.githubusercontent.com/33018206/196964463-066f3473-8d5f-4132-9848-a2d99ff56e03.MP4


## Smartphone (please complete the following information):
 - Device: iPhone 14 Pro
 - OS: iOS 16.0.1
 - Version 0.3.0(8)

**Comment by alinasytnik** [comment] 2022-10-20 14:19
## **⚠️Bug**

## Description
Liquidity Supply cannot be confirmed because Wallet Connect stops identifying the Plug app on the mobile device and redirects the user to the Plug site. 

## Steps to Reproduce
1. Go to Sonic
2. Click on Connect button in the Sonic app
3. Confirm the connection by clicking on Connect button in the Plug app
4. Allow the permissions (It'll take you back to the Sonic app)
5. Go to the Liquidity tab.
6. Choose the liquidity pair. 
7. Click on the Review Supply button.
8. Click on the Confirm Supply button. 
**Current:** Notice that the user is taken to the **plug.ooo** website. 


## Expected behavior
The user should be taken to the Plug Mobile app and able to Confirm Supply. 

## Screenshots

https://user-images.githubusercontent.com/33018206/196973555-794e94a1-a6a3-4796-892d-cdb67ec05948.MP4




## Smartphone (please complete the following information):
 - Device: iPhone 14 Pro
 - OS: iOS 16.0.1
 - Version 0.3.0(8)

## Additional information
Liquidity could be added successfully if the user manually opens Plug Mobile and confirms the permission, and then goes back to the Sonic app. (I've showed this case on the video)

**Comment by alinasytnik** [comment] 2022-10-20 14:27
## **⚠️Bug**

## Description
Assets Deposit cannot be confirmed because Wallet Connect stops identifying the Plug app on the mobile device and redirects the user to the Plug site. 

## Steps to Reproduce
1. Go to Sonic
2. Click on Connect button in the Sonic app
3. Confirm the connection by clicking on Connect button in the Plug app
4. Allow the permissions (It'll take you back to the Sonic app)
5. Go to the Assets tab.
6. Choose the asset to deposit. (Click on the plus icon button)
7. Click on the Deposit button.
**Current:** Notice that the user is taken to the **plug.ooo** website. 


## Expected behavior
The user should be taken to the Plug Mobile app and able to Confirm the Deposit. 

## Screenshots


https://user-images.githubusercontent.com/33018206/196974991-f39ca52c-3a94-4136-9976-0f941930addb.MP4



## Smartphone (please complete the following information):
 - Device: iPhone 14 Pro
 - OS: iOS 16.0.1
 - Version 0.3.0(8)

**Comment by alinasytnik** [comment] 2022-10-24 17:28
## **⚠️Bug**

## Description
Swap, Liquidity Adding, Deposit, and Withdrawal transactions couldn't be processed because of the broken Confirmation button. 

## Steps to Reproduce
1. Go to Sonic
2. Click on Connect button in the Sonic app
3. Confirm the connection by clicking on Connect button in the Plug app
4. Allow the permissions (It'll take you back to the Sonic app)
5. Go to the Swap(Liquidity, Assets) tab.
6. Choose the assets for making a transaction. 
7. Click on the Swap (Review Supply, Deposit, etc.) button. (It'll take you to the Plug app)
8. Click on the Confirm button 
**Current:** Notice that the Confirm button is not clickable. 

## Expected behavior
The Confirm button should be clickable and allow the user to confirm the transaction. 

## Screenshots

https://user-images.githubusercontent.com/33018206/197588127-d2ad26fa-4f9e-4740-b2a1-6aa610418981.mov

https://user-images.githubusercontent.com/33018206/197588249-e52b11d4-ec69-464e-9ddd-78873c2d8f69.MP4


https://user-images.githubusercontent.com/33018206/197588400-9b365b84-2395-4ca8-8e0b-f9275d3df356.mov


https://user-images.githubusercontent.com/33018206/197588568-373fe6ab-dc18-4c77-a688-f07b515322fa.MP4



## Smartphone (please complete the following information):
 - Device: iPhone 14 Pro
 - OS: iOS 16.0.1
 - Version 0.3.0(9)

**Comment by karlamiesesfleek** [comment] 2022-10-28 11:37
## ⚠️Bug

## Description
On the Liquidity screen when creating a position and when adding liquidity to a position, Instead of taking the user to Plug Mobile, the user is taken to https://plugwallet.ooo/.

## Steps to Reproduce

1. Go to Sonic
2. Click on Connect button in the Sonic app
3. Confirm the connection by clicking on Connect button in the Plug app
4. Allow the permissions (It'll take you back to the Sonic app)
5. Go to the Liquidity tab.
6. Create a Liquidity position
7. Click on the Confirm button
8. Current: the user is taken to https://plugwallet.ooo/.

---

## Expected behavior
The user should be taken to Plug app. 

https://user-images.githubusercontent.com/94389748/198578291-8425a17d-522d-4192-ad03-e7bb92e5f025.mp4
---
Smartphone (please complete the following information):
Device: iPhone XS
Version 0.3.0(10)

**Comment by alinasytnik** [comment] 2022-11-03 20:15
## **⚠️Bug**

## Description
When creating and switching to a new Plug account, the wallet doesn't connect to Sonic.

## Steps to Reproduce
1. Go to Sonic
2. Click on Connect button in the Sonic app
3. Click on the Change Wallet button
4. Create a new account
5. Choose this newly created account 
6. Confirm the connection by clicking on Connect button in the Plug app
7. Allow the permissions (It'll take you back to the Sonic app)
**Current:** Notice that the Plug doesn’t connect and still loading.

## Expected behavior
The wallet should be connected. 

## Screenshots

https://user-images.githubusercontent.com/33018206/199823958-0e907a58-a685-4d49-8cc6-6a67644c3160.mov


## Smartphone (please complete the following information):
 - Device: iPhone 14 Pro
 - OS: iOS 16.0.1
 - Version 0.3.0(10)

**Comment by kevin4476** [comment] 2022-11-04 03:33
##⚠️ Bug
--

## Testing Information

- **OS:** Android
- **Cellphone** **version:** Samsung Galaxy Note 9
- **Version Plug mobile:** v0.3.0(24)

## Precondition

- Use this version of Sonic: [https://2aoj2-aaaaa-aaaad-qa4qq-cai.ic.fleek.co/swap](https://2aoj2-aaaaa-aaaad-qa4qq-cai.ic.fleek.co/swap)

---

**Issue:** When I press the button “View in activity tab” found in the success message the app unbind to Plug Mobile

- **Steps to recreate**
    - Launch app
    - Connect Sonic with Plug Mobile
    - To Do any transaction
    - When the transaction end press the button “View in activity tab”
    
- **Current:** The app reloads and unbinds


https://user-images.githubusercontent.com/108067829/199879555-548f1192-7713-4d81-9b00-1e5143fec533.mp4


- **Expected:** The app should take the user to the Activity tab and show the transaction made

**Comment by karlamiesesfleek** [comment] 2022-11-04 15:55
# ⚠️ Bug
## Testing Information
OS: Android/iOS
Cellphone version: Samsung Galaxy Note 8 & iPhone-13
Version Plug mobile: v0.3.0(24)

## Issue
When the app(plug mobile) is locked and closed and the user tries to connect to Sonic, the app is not asking request to connect screen. 
QA's theory: I think the request connection screen is launched but is hidding somewhere. 

### Precondition:
- Close the app (by closing, make sure the app is not running in background)
- App must be locked before closing it
- Turn off the biometrics

**Steps to recreate:**
- Launch Sonic
- Tap on Connect to Plug button
- You're going to be taken to Plug > Type the password

**Current:** 
- Connection request is not showing
- If you close and reopen the app you get "The connection has timed out" 

https://user-images.githubusercontent.com/94389748/200019874-47e668a7-22b0-43fa-9ff2-82c7b3cc0786.mp4

### Expected behavior
- Connection request should appear

**Closed** 2022-11-08 13:45 UTC
Labels: enhancement
